Repository hakadoriya/ddlctl, pull requests merged in 2024-01, with the labels that each got.

#3 chore: Update CREDITS
  CREDITS
Labels: chore

#4 feat: Add apply subcommand
  .envrc.sh
  README.md
  internal/config/auto_approve.go
  internal/config/config.go
  internal/consts/cli.go
  pkg/ddlctl/ddlctl.go
  pkg/ddlctl/ddlctl_apply.go
  pkg/ddlctl/ddlctl_diff.go
  pkg/errors/errors.go
Labels: feat

#5 build(deps): bump github.com/kunitsucom/util.go from 0.0.60-rc.3 to 0.0.60-rc.4
  README.md
  go.mod
  go.sum
  pkg/ddlctl/ddlctl_apply.go
Labels: build

#6 feat: support postgres
  README.md
  go.mod
  go.sum
  internal/integrationtest/integrationtest_test.go
  internal/integrationtest/postgres_after.sql
  internal/integrationtest/postgres_before.sql
  pkg/ddlctl/ddlctl_apply.go
  pkg/ddlctl/ddlctl_diff.go
Labels: feat

#8 docs: Update README.md
  README.md
Labels: docs

#9 docs: Update README.md
  README.md
Labels: docs

#10 docs: Update CREDITS
  .github/workflows/go-lint.yml
  .github/workflows/go-mod-tidy.yml
  .github/workflows/go-test.yml
  .github/workflows/go-vuln.yml
  CREDITS
Labels: docs

#11 feat(pkg/show/spanner): show subcommand supports spanner dialect
  .envrc.sh
  README.md
  go.mod
  go.sum
  pkg/ddlctl/ddlctl.go
  pkg/ddlctl/ddlctl_diff.go
  pkg/ddlctl/ddlctl_show.go
  pkg/ddlctl/import.go
  pkg/internal/config/config.go
  pkg/show/cockroachdb/show_create_all_tables.go
  pkg/show/mysql/show_create_all_tables.go
  pkg/show/postgres/show_create_all_tables.go
  pkg/show/spanner/show_create_all_tables.go
Labels: feat

#12 refactor: refactor consts
  pkg/ddl/cockroachdb/ddl.go
  pkg/ddl/diff-cockroachdb-mysql.sh
  pkg/ddl/mysql/ddl.go
  pkg/ddl/postgres/ddl.go
  pkg/ddlctl/ddlctl.go
  pkg/ddlctl/ddlctl_apply.go
  pkg/ddlctl/ddlctl_diff.go
  pkg/ddlctl/ddlctl_generate.go
  pkg/ddlctl/ddlctl_show.go
  pkg/errors/errors.go
Labels: refactor

#15 fix(pkg/show/spanner): fix PRIMARY KEY logic
  pkg/show/spanner/show_create_all_tables.go
Labels: fix

#16 fix(spanner): fix DDL PK pos
  CREDITS
  README.md
  pkg/ddlctl/ddlctl.go
  pkg/internal/generator/dialect/spanner/create_table.go
  pkg/internal/generator/dialect/spanner/integrationtest_go_001.golden
Labels: fix

#17 docs: Update README.md
  README.md
Labels: docs

#18 fix(postgres): fix show logic
  pkg/show/postgres/show_create_all_tables.go
Labels: fix

#19 docs: Update README.md
  README.md
Labels: docs

#20 docs: Update README.md
  README.md
Labels: docs

#22 docs: add docs/ghostplay.sh
  README.md
  docs/.gitignore
  docs/asciinema.sh
  docs/ghostplay.sh
Labels: docs

#23 fix(mysql): support AUTO_INCREMENT, column COLLATE; fix DEFAULT parser, some data types, ON ACTION parser
  .github/workflows/go-test.yml
  pkg/ddl/cockroachdb/parser.go
  pkg/ddl/mysql/ddl_table.go
  pkg/ddl/mysql/ddl_table_alter.go
  pkg/ddl/mysql/diff_create_table.go
  pkg/ddl/mysql/diff_test.go
  pkg/ddl/mysql/lexar.go
  pkg/ddl/mysql/lexar_test.go
  pkg/ddl/mysql/parser.go
  pkg/ddl/mysql/parser_test.go
  pkg/ddl/postgres/parser.go
  pkg/ddl/spanner/parser.go
  pkg/internal/generator/dialect/mysql/integrationtest_go_001.golden
  pkg/internal/generator/dialect/postgres/integrationtest_go_001.golden
  pkg/internal/generator/dialect/spanner/integrationtest_go_001.golden
  pkg/internal/lang/go/parse.go
  pkg/internal/lang/go/parse_test.go
Labels: fix

#24 docs: Update README.md
  README.md
Labels: docs

#25 test: fix misc
  pkg/internal/lang/go/tests/common.source
Labels: test

#26 ci: fix cover
  .github/workflows/go-test.yml
Labels: ci

#27 fix(mysql): support column CHARACTER SET
  pkg/ddl/mysql/ddl_table.go
  pkg/ddl/mysql/ddl_table_alter.go
  pkg/ddl/mysql/ddl_table_alter_test.go
  pkg/ddl/mysql/diff_create_table.go
  pkg/ddl/mysql/lexar.go
  pkg/ddl/mysql/parser.go
  pkg/ddl/mysql/parser_test.go
Labels: fix

#28 refactor: mod column String() func
  pkg/ddl/cockroachdb/ddl_table.go
  pkg/ddl/mysql/ddl_table.go
  pkg/ddl/mysql/parser_test.go
  pkg/ddl/postgres/ddl_table.go
  pkg/ddl/spanner/ddl_table.go
Labels: refactor

#29 fix: diff logic
  pkg/ddl/mysql/diff_create_table.go
  pkg/ddl/spanner/diff_create_table.go
Labels: fix

#30 feat: support ALTER TABLE options
  pkg/ddl/cockroachdb/ddl_table_alter.go
  pkg/ddl/cockroachdb/ddl_table_alter_test.go
  pkg/ddl/cockroachdb/diff_create_table.go
  pkg/ddl/mysql/ddl_table.go
  pkg/ddl/mysql/ddl_table_alter.go
  pkg/ddl/mysql/ddl_table_alter_test.go
  pkg/ddl/mysql/ddl_table_create.go
  pkg/ddl/mysql/ddl_table_create_test.go
  pkg/ddl/mysql/ddl_table_test.go
  pkg/ddl/mysql/diff_create_table.go
  pkg/ddl/mysql/diff_create_table_test.go
  pkg/ddl/mysql/lexar_test.go
  pkg/ddl/mysql/parser.go
  pkg/ddl/mysql/parser_test.go
  pkg/ddl/postgres/ddl_table_alter.go
  pkg/ddl/postgres/ddl_table_alter_test.go
  pkg/ddl/postgres/diff_create_table.go
  pkg/ddl/spanner/ddl_table_alter.go
  pkg/ddl/spanner/ddl_table_alter_test.go
  pkg/ddl/spanner/diff_create_table.go
Labels: feat
