Repository hakadoriya/ddlctl, pull requests merged in 2024-08, with the labels that each got.

#92 feat: Detailed the errors of the apply subcommand
  pkg/ddlctl/apply/ddlctl_apply.go
Labels: feat

#93 fix: Organized the errors of the apply subcommand
  pkg/ddlctl/apply/ddlctl_apply.go
  pkg/internal/util/remove_comment.go
Labels: fix

#94 chore: Add make target: build
  Makefile
Labels: chore

#95 refactor: Fix misc
  pkg/internal/lang/go/dump_source.go
  pkg/internal/lang/go/extract_source.go
  pkg/internal/lang/go/parse.go
  pkg/internal/lang/go/parse_test.go
Labels: refactor

#96 refactor: Modify to distinguish errors between current and peek
  Makefile
  pkg/ddl/cockroachdb/parser.go
  pkg/ddl/cockroachdb/parser_test.go
  pkg/ddl/errors.go
  pkg/ddl/mysql/parser.go
  pkg/ddl/mysql/parser_test.go
  pkg/ddl/postgres/parser.go
  pkg/ddl/postgres/parser_test.go
  pkg/ddl/spanner/parser.go
  pkg/ddl/spanner/parser_test.go
Labels: refactor

#97 feat: Support CockroachDB Hash-sharded Indexes
  .github/workflows/go-test.yml
  pkg/ddl/cockroachdb/ddl.go
  pkg/ddl/cockroachdb/ddl_index_create.go
  pkg/ddl/cockroachdb/ddl_index_create_test.go
  pkg/ddl/cockroachdb/ddl_table.go
  pkg/ddl/cockroachdb/diff_create_table.go
  pkg/ddl/cockroachdb/diff_create_table_test.go
  pkg/ddl/cockroachdb/diff_test.go
  pkg/ddl/cockroachdb/lexar.go
  pkg/ddl/cockroachdb/parser.go
  pkg/ddl/errors.go
Labels: feat
