Repository hakadoriya/ddlctl, pull requests merged in 2025-03, with the labels that each got.

#111 FIX: Skip unexported fields
  pkg/internal/lang/go/parse.go
Labels: fix

#112 fix: lint
  pkg/ddl/cockroachdb/diff_create_table_test.go
  pkg/ddl/mysql/ddl_table.go
  pkg/ddl/mysql/diff_create_table_test.go
  pkg/ddl/postgres/diff_create_table_test.go
  pkg/ddl/spanner/diff_create_table_test.go
Labels: fix

#116 ci: Update .github/workflows/task-list-checker.yml
  .github/workflows/task-list-checker.yml
Labels: ci

#117 docs: Update CREDITS
  CREDITS
Labels: docs
